<?xml version="1.0" encoding="utf-8"?><Database Name="wifi" Class="DataWifiDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="wifi_ping">
    <Type Name="wifi_ping">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gw_id" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="sys_uptime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sys_memfree" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sys_load" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="auth_soft_uptime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="create_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="wifi_connection">
    <Type Name="wifi_connection">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="wifi_guest_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="gw_id" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="visit_url" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="token" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="is_count" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="guest_type_name" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="guest_login_name" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="guest_nickname" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="create_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="wifi_coupon">
    <Type Name="wifi_coupon">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="batch" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="mobile" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="begin_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="end_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="send_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="is_consume" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="consume_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="merchant_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="wifi_device">
    <Type Name="wifi_device">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gw_id" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="merchant_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="begin_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="end_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="device_name" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="enabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="create_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="wifi_guest_group">
    <Type Name="wifi_guest_group">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="group_name" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="merchant_id" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="wifi_messgerecord">
    <Type Name="wifi_messgerecord">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mobile" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="createtime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="isdelayedsend" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="delayedsendtime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="realsendtime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sendstate" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="merchant_id" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="wifi_admin">
    <Type Name="wifi_admin">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="mobile" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="real_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="state" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="create_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="wifi_template">
    <Type Name="wifi_template">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="merchant_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="template_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="template_data" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="begin_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="end_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="create_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="wifi_blacklist">
    <Type Name="wifi_blacklist">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="merchant_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="login_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="create_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="wifi_merchant">
    <Type Name="wifi_merchant">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="merchant_name" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="city" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="province" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="area" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="address_info" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="longitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="latitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="contact_name" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="contact_phone" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="user_password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sms_count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="time_interval" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="surfing_time" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="old_guest_times" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="auth_type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="weibo_id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="qq_weibo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="welcome_text" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="template_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="create_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="admin_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="wifi_guest">
    <Type Name="wifi_guest">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="wifi_guest_type_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="wifi_guest_group_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="login_name" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="is_verfiymobile" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="nickname" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="province_name" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="city_name" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="merchant_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="last_login_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="last_login_token" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="last_gw_id" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="last_ip" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="last_mac" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="last_incoming" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="last_outgoing" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="last_stage" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="last_update_time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="is_employee" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_online" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_goout" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="create_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>