#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jujin.Dao
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="wifi")]
	public partial class DataWifiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertwifi_ping(wifi_ping instance);
    partial void Updatewifi_ping(wifi_ping instance);
    partial void Deletewifi_ping(wifi_ping instance);
    partial void Insertwifi_connection(wifi_connection instance);
    partial void Updatewifi_connection(wifi_connection instance);
    partial void Deletewifi_connection(wifi_connection instance);
    partial void Insertwifi_coupon(wifi_coupon instance);
    partial void Updatewifi_coupon(wifi_coupon instance);
    partial void Deletewifi_coupon(wifi_coupon instance);
    partial void Insertwifi_device(wifi_device instance);
    partial void Updatewifi_device(wifi_device instance);
    partial void Deletewifi_device(wifi_device instance);
    partial void Insertwifi_guest_group(wifi_guest_group instance);
    partial void Updatewifi_guest_group(wifi_guest_group instance);
    partial void Deletewifi_guest_group(wifi_guest_group instance);
    partial void Insertwifi_messgerecord(wifi_messgerecord instance);
    partial void Updatewifi_messgerecord(wifi_messgerecord instance);
    partial void Deletewifi_messgerecord(wifi_messgerecord instance);
    partial void Insertwifi_admin(wifi_admin instance);
    partial void Updatewifi_admin(wifi_admin instance);
    partial void Deletewifi_admin(wifi_admin instance);
    partial void Insertwifi_template(wifi_template instance);
    partial void Updatewifi_template(wifi_template instance);
    partial void Deletewifi_template(wifi_template instance);
    partial void Insertwifi_blacklist(wifi_blacklist instance);
    partial void Updatewifi_blacklist(wifi_blacklist instance);
    partial void Deletewifi_blacklist(wifi_blacklist instance);
    partial void Insertwifi_merchant(wifi_merchant instance);
    partial void Updatewifi_merchant(wifi_merchant instance);
    partial void Deletewifi_merchant(wifi_merchant instance);
    partial void Insertwifi_guest(wifi_guest instance);
    partial void Updatewifi_guest(wifi_guest instance);
    partial void Deletewifi_guest(wifi_guest instance);
    #endregion
		
		public DataWifiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataWifiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataWifiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataWifiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<wifi_ping> wifi_ping
		{
			get
			{
				return this.GetTable<wifi_ping>();
			}
		}
		
		public System.Data.Linq.Table<wifi_connection> wifi_connection
		{
			get
			{
				return this.GetTable<wifi_connection>();
			}
		}
		
		public System.Data.Linq.Table<wifi_coupon> wifi_coupon
		{
			get
			{
				return this.GetTable<wifi_coupon>();
			}
		}
		
		public System.Data.Linq.Table<wifi_device> wifi_device
		{
			get
			{
				return this.GetTable<wifi_device>();
			}
		}
		
		public System.Data.Linq.Table<wifi_guest_group> wifi_guest_group
		{
			get
			{
				return this.GetTable<wifi_guest_group>();
			}
		}
		
		public System.Data.Linq.Table<wifi_messgerecord> wifi_messgerecord
		{
			get
			{
				return this.GetTable<wifi_messgerecord>();
			}
		}
		
		public System.Data.Linq.Table<wifi_admin> wifi_admin
		{
			get
			{
				return this.GetTable<wifi_admin>();
			}
		}
		
		public System.Data.Linq.Table<wifi_template> wifi_template
		{
			get
			{
				return this.GetTable<wifi_template>();
			}
		}
		
		public System.Data.Linq.Table<wifi_blacklist> wifi_blacklist
		{
			get
			{
				return this.GetTable<wifi_blacklist>();
			}
		}
		
		public System.Data.Linq.Table<wifi_merchant> wifi_merchant
		{
			get
			{
				return this.GetTable<wifi_merchant>();
			}
		}
		
		public System.Data.Linq.Table<wifi_guest> wifi_guest
		{
			get
			{
				return this.GetTable<wifi_guest>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class wifi_ping : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _gw_id;
		
		private System.Nullable<int> _sys_uptime;
		
		private System.Nullable<int> _sys_memfree;
		
		private System.Nullable<double> _sys_load;
		
		private System.Nullable<int> _auth_soft_uptime;
		
		private System.DateTime _create_time;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Ongw_idChanging(string value);
    partial void Ongw_idChanged();
    partial void Onsys_uptimeChanging(System.Nullable<int> value);
    partial void Onsys_uptimeChanged();
    partial void Onsys_memfreeChanging(System.Nullable<int> value);
    partial void Onsys_memfreeChanged();
    partial void Onsys_loadChanging(System.Nullable<double> value);
    partial void Onsys_loadChanged();
    partial void Onauth_soft_uptimeChanging(System.Nullable<int> value);
    partial void Onauth_soft_uptimeChanged();
    partial void Oncreate_timeChanging(System.DateTime value);
    partial void Oncreate_timeChanged();
    #endregion
		
		public wifi_ping()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gw_id", DbType="VarChar(32)")]
		public string gw_id
		{
			get
			{
				return this._gw_id;
			}
			set
			{
				if ((this._gw_id != value))
				{
					this.Ongw_idChanging(value);
					this.SendPropertyChanging();
					this._gw_id = value;
					this.SendPropertyChanged("gw_id");
					this.Ongw_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sys_uptime", DbType="Int")]
		public System.Nullable<int> sys_uptime
		{
			get
			{
				return this._sys_uptime;
			}
			set
			{
				if ((this._sys_uptime != value))
				{
					this.Onsys_uptimeChanging(value);
					this.SendPropertyChanging();
					this._sys_uptime = value;
					this.SendPropertyChanged("sys_uptime");
					this.Onsys_uptimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sys_memfree", DbType="Int")]
		public System.Nullable<int> sys_memfree
		{
			get
			{
				return this._sys_memfree;
			}
			set
			{
				if ((this._sys_memfree != value))
				{
					this.Onsys_memfreeChanging(value);
					this.SendPropertyChanging();
					this._sys_memfree = value;
					this.SendPropertyChanged("sys_memfree");
					this.Onsys_memfreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sys_load", DbType="Float")]
		public System.Nullable<double> sys_load
		{
			get
			{
				return this._sys_load;
			}
			set
			{
				if ((this._sys_load != value))
				{
					this.Onsys_loadChanging(value);
					this.SendPropertyChanging();
					this._sys_load = value;
					this.SendPropertyChanged("sys_load");
					this.Onsys_loadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auth_soft_uptime", DbType="Int")]
		public System.Nullable<int> auth_soft_uptime
		{
			get
			{
				return this._auth_soft_uptime;
			}
			set
			{
				if ((this._auth_soft_uptime != value))
				{
					this.Onauth_soft_uptimeChanging(value);
					this.SendPropertyChanging();
					this._auth_soft_uptime = value;
					this.SendPropertyChanged("auth_soft_uptime");
					this.Onauth_soft_uptimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_time", DbType="DateTime NOT NULL")]
		public System.DateTime create_time
		{
			get
			{
				return this._create_time;
			}
			set
			{
				if ((this._create_time != value))
				{
					this.Oncreate_timeChanging(value);
					this.SendPropertyChanging();
					this._create_time = value;
					this.SendPropertyChanged("create_time");
					this.Oncreate_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class wifi_connection : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _wifi_guest_id;
		
		private string _gw_id;
		
		private string _visit_url;
		
		private string _token;
		
		private System.Nullable<bool> _is_count;
		
		private string _guest_type_name;
		
		private string _guest_login_name;
		
		private string _guest_nickname;
		
		private System.DateTime _create_time;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onwifi_guest_idChanging(int value);
    partial void Onwifi_guest_idChanged();
    partial void Ongw_idChanging(string value);
    partial void Ongw_idChanged();
    partial void Onvisit_urlChanging(string value);
    partial void Onvisit_urlChanged();
    partial void OntokenChanging(string value);
    partial void OntokenChanged();
    partial void Onis_countChanging(System.Nullable<bool> value);
    partial void Onis_countChanged();
    partial void Onguest_type_nameChanging(string value);
    partial void Onguest_type_nameChanged();
    partial void Onguest_login_nameChanging(string value);
    partial void Onguest_login_nameChanged();
    partial void Onguest_nicknameChanging(string value);
    partial void Onguest_nicknameChanged();
    partial void Oncreate_timeChanging(System.DateTime value);
    partial void Oncreate_timeChanged();
    #endregion
		
		public wifi_connection()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wifi_guest_id", DbType="Int NOT NULL")]
		public int wifi_guest_id
		{
			get
			{
				return this._wifi_guest_id;
			}
			set
			{
				if ((this._wifi_guest_id != value))
				{
					this.Onwifi_guest_idChanging(value);
					this.SendPropertyChanging();
					this._wifi_guest_id = value;
					this.SendPropertyChanged("wifi_guest_id");
					this.Onwifi_guest_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gw_id", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string gw_id
		{
			get
			{
				return this._gw_id;
			}
			set
			{
				if ((this._gw_id != value))
				{
					this.Ongw_idChanging(value);
					this.SendPropertyChanging();
					this._gw_id = value;
					this.SendPropertyChanged("gw_id");
					this.Ongw_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_url", DbType="VarChar(200)")]
		public string visit_url
		{
			get
			{
				return this._visit_url;
			}
			set
			{
				if ((this._visit_url != value))
				{
					this.Onvisit_urlChanging(value);
					this.SendPropertyChanging();
					this._visit_url = value;
					this.SendPropertyChanged("visit_url");
					this.Onvisit_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_token", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string token
		{
			get
			{
				return this._token;
			}
			set
			{
				if ((this._token != value))
				{
					this.OntokenChanging(value);
					this.SendPropertyChanging();
					this._token = value;
					this.SendPropertyChanged("token");
					this.OntokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_count", DbType="Bit")]
		public System.Nullable<bool> is_count
		{
			get
			{
				return this._is_count;
			}
			set
			{
				if ((this._is_count != value))
				{
					this.Onis_countChanging(value);
					this.SendPropertyChanging();
					this._is_count = value;
					this.SendPropertyChanged("is_count");
					this.Onis_countChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guest_type_name", DbType="VarChar(45)")]
		public string guest_type_name
		{
			get
			{
				return this._guest_type_name;
			}
			set
			{
				if ((this._guest_type_name != value))
				{
					this.Onguest_type_nameChanging(value);
					this.SendPropertyChanging();
					this._guest_type_name = value;
					this.SendPropertyChanged("guest_type_name");
					this.Onguest_type_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guest_login_name", DbType="VarChar(45)")]
		public string guest_login_name
		{
			get
			{
				return this._guest_login_name;
			}
			set
			{
				if ((this._guest_login_name != value))
				{
					this.Onguest_login_nameChanging(value);
					this.SendPropertyChanging();
					this._guest_login_name = value;
					this.SendPropertyChanged("guest_login_name");
					this.Onguest_login_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guest_nickname", DbType="VarChar(45)")]
		public string guest_nickname
		{
			get
			{
				return this._guest_nickname;
			}
			set
			{
				if ((this._guest_nickname != value))
				{
					this.Onguest_nicknameChanging(value);
					this.SendPropertyChanging();
					this._guest_nickname = value;
					this.SendPropertyChanged("guest_nickname");
					this.Onguest_nicknameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_time", DbType="DateTime NOT NULL")]
		public System.DateTime create_time
		{
			get
			{
				return this._create_time;
			}
			set
			{
				if ((this._create_time != value))
				{
					this.Oncreate_timeChanging(value);
					this.SendPropertyChanging();
					this._create_time = value;
					this.SendPropertyChanged("create_time");
					this.Oncreate_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class wifi_coupon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _batch;
		
		private string _title;
		
		private string _code;
		
		private string _mobile;
		
		private System.DateTime _begin_time;
		
		private System.DateTime _end_time;
		
		private System.DateTime _send_time;
		
		private bool _is_consume;
		
		private System.Nullable<System.DateTime> _consume_time;
		
		private int _merchant_id;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnbatchChanging(string value);
    partial void OnbatchChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OnmobileChanging(string value);
    partial void OnmobileChanged();
    partial void Onbegin_timeChanging(System.DateTime value);
    partial void Onbegin_timeChanged();
    partial void Onend_timeChanging(System.DateTime value);
    partial void Onend_timeChanged();
    partial void Onsend_timeChanging(System.DateTime value);
    partial void Onsend_timeChanged();
    partial void Onis_consumeChanging(bool value);
    partial void Onis_consumeChanged();
    partial void Onconsume_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onconsume_timeChanged();
    partial void Onmerchant_idChanging(int value);
    partial void Onmerchant_idChanged();
    #endregion
		
		public wifi_coupon()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_batch", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string batch
		{
			get
			{
				return this._batch;
			}
			set
			{
				if ((this._batch != value))
				{
					this.OnbatchChanging(value);
					this.SendPropertyChanging();
					this._batch = value;
					this.SendPropertyChanged("batch");
					this.OnbatchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string mobile
		{
			get
			{
				return this._mobile;
			}
			set
			{
				if ((this._mobile != value))
				{
					this.OnmobileChanging(value);
					this.SendPropertyChanging();
					this._mobile = value;
					this.SendPropertyChanged("mobile");
					this.OnmobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_begin_time", DbType="DateTime NOT NULL")]
		public System.DateTime begin_time
		{
			get
			{
				return this._begin_time;
			}
			set
			{
				if ((this._begin_time != value))
				{
					this.Onbegin_timeChanging(value);
					this.SendPropertyChanging();
					this._begin_time = value;
					this.SendPropertyChanged("begin_time");
					this.Onbegin_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_time", DbType="DateTime NOT NULL")]
		public System.DateTime end_time
		{
			get
			{
				return this._end_time;
			}
			set
			{
				if ((this._end_time != value))
				{
					this.Onend_timeChanging(value);
					this.SendPropertyChanging();
					this._end_time = value;
					this.SendPropertyChanged("end_time");
					this.Onend_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_send_time", DbType="DateTime NOT NULL")]
		public System.DateTime send_time
		{
			get
			{
				return this._send_time;
			}
			set
			{
				if ((this._send_time != value))
				{
					this.Onsend_timeChanging(value);
					this.SendPropertyChanging();
					this._send_time = value;
					this.SendPropertyChanged("send_time");
					this.Onsend_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_consume", DbType="Bit NOT NULL")]
		public bool is_consume
		{
			get
			{
				return this._is_consume;
			}
			set
			{
				if ((this._is_consume != value))
				{
					this.Onis_consumeChanging(value);
					this.SendPropertyChanging();
					this._is_consume = value;
					this.SendPropertyChanged("is_consume");
					this.Onis_consumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_consume_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> consume_time
		{
			get
			{
				return this._consume_time;
			}
			set
			{
				if ((this._consume_time != value))
				{
					this.Onconsume_timeChanging(value);
					this.SendPropertyChanging();
					this._consume_time = value;
					this.SendPropertyChanged("consume_time");
					this.Onconsume_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_merchant_id", DbType="Int NOT NULL")]
		public int merchant_id
		{
			get
			{
				return this._merchant_id;
			}
			set
			{
				if ((this._merchant_id != value))
				{
					this.Onmerchant_idChanging(value);
					this.SendPropertyChanging();
					this._merchant_id = value;
					this.SendPropertyChanged("merchant_id");
					this.Onmerchant_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class wifi_device : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _gw_id;
		
		private int _merchant_id;
		
		private System.DateTime _begin_time;
		
		private System.DateTime _end_time;
		
		private string _device_name;
		
		private System.Nullable<bool> _enabled;
		
		private System.DateTime _create_time;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Ongw_idChanging(string value);
    partial void Ongw_idChanged();
    partial void Onmerchant_idChanging(int value);
    partial void Onmerchant_idChanged();
    partial void Onbegin_timeChanging(System.DateTime value);
    partial void Onbegin_timeChanged();
    partial void Onend_timeChanging(System.DateTime value);
    partial void Onend_timeChanged();
    partial void Ondevice_nameChanging(string value);
    partial void Ondevice_nameChanged();
    partial void OnenabledChanging(System.Nullable<bool> value);
    partial void OnenabledChanged();
    partial void Oncreate_timeChanging(System.DateTime value);
    partial void Oncreate_timeChanged();
    #endregion
		
		public wifi_device()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gw_id", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string gw_id
		{
			get
			{
				return this._gw_id;
			}
			set
			{
				if ((this._gw_id != value))
				{
					this.Ongw_idChanging(value);
					this.SendPropertyChanging();
					this._gw_id = value;
					this.SendPropertyChanged("gw_id");
					this.Ongw_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_merchant_id", DbType="Int NOT NULL")]
		public int merchant_id
		{
			get
			{
				return this._merchant_id;
			}
			set
			{
				if ((this._merchant_id != value))
				{
					this.Onmerchant_idChanging(value);
					this.SendPropertyChanging();
					this._merchant_id = value;
					this.SendPropertyChanged("merchant_id");
					this.Onmerchant_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_begin_time", DbType="DateTime NOT NULL")]
		public System.DateTime begin_time
		{
			get
			{
				return this._begin_time;
			}
			set
			{
				if ((this._begin_time != value))
				{
					this.Onbegin_timeChanging(value);
					this.SendPropertyChanging();
					this._begin_time = value;
					this.SendPropertyChanged("begin_time");
					this.Onbegin_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_time", DbType="DateTime NOT NULL")]
		public System.DateTime end_time
		{
			get
			{
				return this._end_time;
			}
			set
			{
				if ((this._end_time != value))
				{
					this.Onend_timeChanging(value);
					this.SendPropertyChanging();
					this._end_time = value;
					this.SendPropertyChanged("end_time");
					this.Onend_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_device_name", DbType="VarChar(45)")]
		public string device_name
		{
			get
			{
				return this._device_name;
			}
			set
			{
				if ((this._device_name != value))
				{
					this.Ondevice_nameChanging(value);
					this.SendPropertyChanging();
					this._device_name = value;
					this.SendPropertyChanged("device_name");
					this.Ondevice_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enabled", DbType="Bit")]
		public System.Nullable<bool> enabled
		{
			get
			{
				return this._enabled;
			}
			set
			{
				if ((this._enabled != value))
				{
					this.OnenabledChanging(value);
					this.SendPropertyChanging();
					this._enabled = value;
					this.SendPropertyChanged("enabled");
					this.OnenabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_time", DbType="DateTime NOT NULL")]
		public System.DateTime create_time
		{
			get
			{
				return this._create_time;
			}
			set
			{
				if ((this._create_time != value))
				{
					this.Oncreate_timeChanging(value);
					this.SendPropertyChanging();
					this._create_time = value;
					this.SendPropertyChanged("create_time");
					this.Oncreate_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class wifi_guest_group : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _group_name;
		
		private string _merchant_id;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Ongroup_nameChanging(string value);
    partial void Ongroup_nameChanged();
    partial void Onmerchant_idChanging(string value);
    partial void Onmerchant_idChanged();
    #endregion
		
		public wifi_guest_group()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_group_name", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string group_name
		{
			get
			{
				return this._group_name;
			}
			set
			{
				if ((this._group_name != value))
				{
					this.Ongroup_nameChanging(value);
					this.SendPropertyChanging();
					this._group_name = value;
					this.SendPropertyChanged("group_name");
					this.Ongroup_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_merchant_id", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string merchant_id
		{
			get
			{
				return this._merchant_id;
			}
			set
			{
				if ((this._merchant_id != value))
				{
					this.Onmerchant_idChanging(value);
					this.SendPropertyChanging();
					this._merchant_id = value;
					this.SendPropertyChanged("merchant_id");
					this.Onmerchant_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class wifi_messgerecord : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _mobile;
		
		private string _content;
		
		private System.DateTime _createtime;
		
		private bool _isdelayedsend;
		
		private System.Nullable<System.DateTime> _delayedsendtime;
		
		private System.Nullable<System.DateTime> _realsendtime;
		
		private System.Nullable<short> _sendstate;
		
		private string _merchant_id;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmobileChanging(string value);
    partial void OnmobileChanged();
    partial void OncontentChanging(string value);
    partial void OncontentChanged();
    partial void OncreatetimeChanging(System.DateTime value);
    partial void OncreatetimeChanged();
    partial void OnisdelayedsendChanging(bool value);
    partial void OnisdelayedsendChanged();
    partial void OndelayedsendtimeChanging(System.Nullable<System.DateTime> value);
    partial void OndelayedsendtimeChanged();
    partial void OnrealsendtimeChanging(System.Nullable<System.DateTime> value);
    partial void OnrealsendtimeChanged();
    partial void OnsendstateChanging(System.Nullable<short> value);
    partial void OnsendstateChanged();
    partial void Onmerchant_idChanging(string value);
    partial void Onmerchant_idChanged();
    #endregion
		
		public wifi_messgerecord()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string mobile
		{
			get
			{
				return this._mobile;
			}
			set
			{
				if ((this._mobile != value))
				{
					this.OnmobileChanging(value);
					this.SendPropertyChanging();
					this._mobile = value;
					this.SendPropertyChanged("mobile");
					this.OnmobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="VarChar(500)")]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this.OncontentChanging(value);
					this.SendPropertyChanging();
					this._content = value;
					this.SendPropertyChanged("content");
					this.OncontentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createtime", DbType="DateTime NOT NULL")]
		public System.DateTime createtime
		{
			get
			{
				return this._createtime;
			}
			set
			{
				if ((this._createtime != value))
				{
					this.OncreatetimeChanging(value);
					this.SendPropertyChanging();
					this._createtime = value;
					this.SendPropertyChanged("createtime");
					this.OncreatetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isdelayedsend", DbType="Bit NOT NULL")]
		public bool isdelayedsend
		{
			get
			{
				return this._isdelayedsend;
			}
			set
			{
				if ((this._isdelayedsend != value))
				{
					this.OnisdelayedsendChanging(value);
					this.SendPropertyChanging();
					this._isdelayedsend = value;
					this.SendPropertyChanged("isdelayedsend");
					this.OnisdelayedsendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delayedsendtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> delayedsendtime
		{
			get
			{
				return this._delayedsendtime;
			}
			set
			{
				if ((this._delayedsendtime != value))
				{
					this.OndelayedsendtimeChanging(value);
					this.SendPropertyChanging();
					this._delayedsendtime = value;
					this.SendPropertyChanged("delayedsendtime");
					this.OndelayedsendtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_realsendtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> realsendtime
		{
			get
			{
				return this._realsendtime;
			}
			set
			{
				if ((this._realsendtime != value))
				{
					this.OnrealsendtimeChanging(value);
					this.SendPropertyChanging();
					this._realsendtime = value;
					this.SendPropertyChanged("realsendtime");
					this.OnrealsendtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sendstate", DbType="SmallInt")]
		public System.Nullable<short> sendstate
		{
			get
			{
				return this._sendstate;
			}
			set
			{
				if ((this._sendstate != value))
				{
					this.OnsendstateChanging(value);
					this.SendPropertyChanging();
					this._sendstate = value;
					this.SendPropertyChanged("sendstate");
					this.OnsendstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_merchant_id", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string merchant_id
		{
			get
			{
				return this._merchant_id;
			}
			set
			{
				if ((this._merchant_id != value))
				{
					this.Onmerchant_idChanging(value);
					this.SendPropertyChanging();
					this._merchant_id = value;
					this.SendPropertyChanged("merchant_id");
					this.Onmerchant_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class wifi_admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _user_name;
		
		private string _password;
		
		private string _mobile;
		
		private string _real_name;
		
		private byte _state;
		
		private System.Nullable<System.DateTime> _create_time;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnmobileChanging(string value);
    partial void OnmobileChanged();
    partial void Onreal_nameChanging(string value);
    partial void Onreal_nameChanged();
    partial void OnstateChanging(byte value);
    partial void OnstateChanged();
    partial void Oncreate_timeChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_timeChanged();
    #endregion
		
		public wifi_admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="VarChar(50)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="VarChar(50)")]
		public string mobile
		{
			get
			{
				return this._mobile;
			}
			set
			{
				if ((this._mobile != value))
				{
					this.OnmobileChanging(value);
					this.SendPropertyChanging();
					this._mobile = value;
					this.SendPropertyChanged("mobile");
					this.OnmobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_real_name", DbType="VarChar(50)")]
		public string real_name
		{
			get
			{
				return this._real_name;
			}
			set
			{
				if ((this._real_name != value))
				{
					this.Onreal_nameChanging(value);
					this.SendPropertyChanging();
					this._real_name = value;
					this.SendPropertyChanged("real_name");
					this.Onreal_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="TinyInt NOT NULL")]
		public byte state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_time
		{
			get
			{
				return this._create_time;
			}
			set
			{
				if ((this._create_time != value))
				{
					this.Oncreate_timeChanging(value);
					this.SendPropertyChanging();
					this._create_time = value;
					this.SendPropertyChanged("create_time");
					this.Oncreate_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class wifi_template : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _merchant_id;
		
		private string _template_name;
		
		private string _template_data;
		
		private System.Nullable<System.DateTime> _begin_time;
		
		private System.Nullable<System.DateTime> _end_time;
		
		private System.Nullable<System.DateTime> _create_time;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onmerchant_idChanging(int value);
    partial void Onmerchant_idChanged();
    partial void Ontemplate_nameChanging(string value);
    partial void Ontemplate_nameChanged();
    partial void Ontemplate_dataChanging(string value);
    partial void Ontemplate_dataChanged();
    partial void Onbegin_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onbegin_timeChanged();
    partial void Onend_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onend_timeChanged();
    partial void Oncreate_timeChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_timeChanged();
    #endregion
		
		public wifi_template()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_merchant_id", DbType="Int NOT NULL")]
		public int merchant_id
		{
			get
			{
				return this._merchant_id;
			}
			set
			{
				if ((this._merchant_id != value))
				{
					this.Onmerchant_idChanging(value);
					this.SendPropertyChanging();
					this._merchant_id = value;
					this.SendPropertyChanged("merchant_id");
					this.Onmerchant_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_template_name", DbType="VarChar(50)")]
		public string template_name
		{
			get
			{
				return this._template_name;
			}
			set
			{
				if ((this._template_name != value))
				{
					this.Ontemplate_nameChanging(value);
					this.SendPropertyChanging();
					this._template_name = value;
					this.SendPropertyChanged("template_name");
					this.Ontemplate_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_template_data", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string template_data
		{
			get
			{
				return this._template_data;
			}
			set
			{
				if ((this._template_data != value))
				{
					this.Ontemplate_dataChanging(value);
					this.SendPropertyChanging();
					this._template_data = value;
					this.SendPropertyChanged("template_data");
					this.Ontemplate_dataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_begin_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> begin_time
		{
			get
			{
				return this._begin_time;
			}
			set
			{
				if ((this._begin_time != value))
				{
					this.Onbegin_timeChanging(value);
					this.SendPropertyChanging();
					this._begin_time = value;
					this.SendPropertyChanged("begin_time");
					this.Onbegin_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> end_time
		{
			get
			{
				return this._end_time;
			}
			set
			{
				if ((this._end_time != value))
				{
					this.Onend_timeChanging(value);
					this.SendPropertyChanging();
					this._end_time = value;
					this.SendPropertyChanged("end_time");
					this.Onend_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_time
		{
			get
			{
				return this._create_time;
			}
			set
			{
				if ((this._create_time != value))
				{
					this.Oncreate_timeChanging(value);
					this.SendPropertyChanging();
					this._create_time = value;
					this.SendPropertyChanged("create_time");
					this.Oncreate_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class wifi_blacklist : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _merchant_id;
		
		private string _login_name;
		
		private System.Nullable<System.DateTime> _create_time;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onmerchant_idChanging(int value);
    partial void Onmerchant_idChanged();
    partial void Onlogin_nameChanging(string value);
    partial void Onlogin_nameChanged();
    partial void Oncreate_timeChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_timeChanged();
    #endregion
		
		public wifi_blacklist()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_merchant_id", DbType="Int NOT NULL")]
		public int merchant_id
		{
			get
			{
				return this._merchant_id;
			}
			set
			{
				if ((this._merchant_id != value))
				{
					this.Onmerchant_idChanging(value);
					this.SendPropertyChanging();
					this._merchant_id = value;
					this.SendPropertyChanged("merchant_id");
					this.Onmerchant_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login_name", DbType="VarChar(50)")]
		public string login_name
		{
			get
			{
				return this._login_name;
			}
			set
			{
				if ((this._login_name != value))
				{
					this.Onlogin_nameChanging(value);
					this.SendPropertyChanging();
					this._login_name = value;
					this.SendPropertyChanged("login_name");
					this.Onlogin_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_time
		{
			get
			{
				return this._create_time;
			}
			set
			{
				if ((this._create_time != value))
				{
					this.Oncreate_timeChanging(value);
					this.SendPropertyChanging();
					this._create_time = value;
					this.SendPropertyChanged("create_time");
					this.Oncreate_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class wifi_merchant : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _merchant_name;
		
		private string _city;
		
		private string _province;
		
		private string _area;
		
		private string _address_info;
		
		private System.Nullable<double> _longitude;
		
		private System.Nullable<double> _latitude;
		
		private string _contact_name;
		
		private string _contact_phone;
		
		private string _username;
		
		private string _user_password;
		
		private int _sms_count;
		
		private byte _time_interval;
		
		private byte _surfing_time;
		
		private int _old_guest_times;
		
		private string _auth_type;
		
		private string _weibo_id;
		
		private string _qq_weibo;
		
		private string _welcome_text;
		
		private string _template_name;
		
		private System.DateTime _create_time;
		
		private System.Nullable<int> _admin_id;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onmerchant_nameChanging(string value);
    partial void Onmerchant_nameChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnprovinceChanging(string value);
    partial void OnprovinceChanged();
    partial void OnareaChanging(string value);
    partial void OnareaChanged();
    partial void Onaddress_infoChanging(string value);
    partial void Onaddress_infoChanged();
    partial void OnlongitudeChanging(System.Nullable<double> value);
    partial void OnlongitudeChanged();
    partial void OnlatitudeChanging(System.Nullable<double> value);
    partial void OnlatitudeChanged();
    partial void Oncontact_nameChanging(string value);
    partial void Oncontact_nameChanged();
    partial void Oncontact_phoneChanging(string value);
    partial void Oncontact_phoneChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void Onuser_passwordChanging(string value);
    partial void Onuser_passwordChanged();
    partial void Onsms_countChanging(int value);
    partial void Onsms_countChanged();
    partial void Ontime_intervalChanging(byte value);
    partial void Ontime_intervalChanged();
    partial void Onsurfing_timeChanging(byte value);
    partial void Onsurfing_timeChanged();
    partial void Onold_guest_timesChanging(int value);
    partial void Onold_guest_timesChanged();
    partial void Onauth_typeChanging(string value);
    partial void Onauth_typeChanged();
    partial void Onweibo_idChanging(string value);
    partial void Onweibo_idChanged();
    partial void Onqq_weiboChanging(string value);
    partial void Onqq_weiboChanged();
    partial void Onwelcome_textChanging(string value);
    partial void Onwelcome_textChanged();
    partial void Ontemplate_nameChanging(string value);
    partial void Ontemplate_nameChanged();
    partial void Oncreate_timeChanging(System.DateTime value);
    partial void Oncreate_timeChanged();
    partial void Onadmin_idChanging(System.Nullable<int> value);
    partial void Onadmin_idChanged();
    #endregion
		
		public wifi_merchant()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_merchant_name", DbType="VarChar(512) NOT NULL", CanBeNull=false)]
		public string merchant_name
		{
			get
			{
				return this._merchant_name;
			}
			set
			{
				if ((this._merchant_name != value))
				{
					this.Onmerchant_nameChanging(value);
					this.SendPropertyChanging();
					this._merchant_name = value;
					this.SendPropertyChanged("merchant_name");
					this.Onmerchant_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string province
		{
			get
			{
				return this._province;
			}
			set
			{
				if ((this._province != value))
				{
					this.OnprovinceChanging(value);
					this.SendPropertyChanging();
					this._province = value;
					this.SendPropertyChanged("province");
					this.OnprovinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area", DbType="VarChar(64)")]
		public string area
		{
			get
			{
				return this._area;
			}
			set
			{
				if ((this._area != value))
				{
					this.OnareaChanging(value);
					this.SendPropertyChanging();
					this._area = value;
					this.SendPropertyChanged("area");
					this.OnareaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address_info", DbType="VarChar(256) NOT NULL", CanBeNull=false)]
		public string address_info
		{
			get
			{
				return this._address_info;
			}
			set
			{
				if ((this._address_info != value))
				{
					this.Onaddress_infoChanging(value);
					this.SendPropertyChanging();
					this._address_info = value;
					this.SendPropertyChanged("address_info");
					this.Onaddress_infoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitude", DbType="Float")]
		public System.Nullable<double> longitude
		{
			get
			{
				return this._longitude;
			}
			set
			{
				if ((this._longitude != value))
				{
					this.OnlongitudeChanging(value);
					this.SendPropertyChanging();
					this._longitude = value;
					this.SendPropertyChanged("longitude");
					this.OnlongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitude", DbType="Float")]
		public System.Nullable<double> latitude
		{
			get
			{
				return this._latitude;
			}
			set
			{
				if ((this._latitude != value))
				{
					this.OnlatitudeChanging(value);
					this.SendPropertyChanging();
					this._latitude = value;
					this.SendPropertyChanged("latitude");
					this.OnlatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_name", DbType="VarChar(500)")]
		public string contact_name
		{
			get
			{
				return this._contact_name;
			}
			set
			{
				if ((this._contact_name != value))
				{
					this.Oncontact_nameChanging(value);
					this.SendPropertyChanging();
					this._contact_name = value;
					this.SendPropertyChanged("contact_name");
					this.Oncontact_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_phone", DbType="VarChar(500)")]
		public string contact_phone
		{
			get
			{
				return this._contact_phone;
			}
			set
			{
				if ((this._contact_phone != value))
				{
					this.Oncontact_phoneChanging(value);
					this.SendPropertyChanging();
					this._contact_phone = value;
					this.SendPropertyChanged("contact_phone");
					this.Oncontact_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string user_password
		{
			get
			{
				return this._user_password;
			}
			set
			{
				if ((this._user_password != value))
				{
					this.Onuser_passwordChanging(value);
					this.SendPropertyChanging();
					this._user_password = value;
					this.SendPropertyChanged("user_password");
					this.Onuser_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sms_count", DbType="Int NOT NULL")]
		public int sms_count
		{
			get
			{
				return this._sms_count;
			}
			set
			{
				if ((this._sms_count != value))
				{
					this.Onsms_countChanging(value);
					this.SendPropertyChanging();
					this._sms_count = value;
					this.SendPropertyChanged("sms_count");
					this.Onsms_countChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time_interval", DbType="TinyInt NOT NULL")]
		public byte time_interval
		{
			get
			{
				return this._time_interval;
			}
			set
			{
				if ((this._time_interval != value))
				{
					this.Ontime_intervalChanging(value);
					this.SendPropertyChanging();
					this._time_interval = value;
					this.SendPropertyChanged("time_interval");
					this.Ontime_intervalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_surfing_time", DbType="TinyInt NOT NULL")]
		public byte surfing_time
		{
			get
			{
				return this._surfing_time;
			}
			set
			{
				if ((this._surfing_time != value))
				{
					this.Onsurfing_timeChanging(value);
					this.SendPropertyChanging();
					this._surfing_time = value;
					this.SendPropertyChanged("surfing_time");
					this.Onsurfing_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_old_guest_times", DbType="Int NOT NULL")]
		public int old_guest_times
		{
			get
			{
				return this._old_guest_times;
			}
			set
			{
				if ((this._old_guest_times != value))
				{
					this.Onold_guest_timesChanging(value);
					this.SendPropertyChanging();
					this._old_guest_times = value;
					this.SendPropertyChanged("old_guest_times");
					this.Onold_guest_timesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auth_type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string auth_type
		{
			get
			{
				return this._auth_type;
			}
			set
			{
				if ((this._auth_type != value))
				{
					this.Onauth_typeChanging(value);
					this.SendPropertyChanging();
					this._auth_type = value;
					this.SendPropertyChanged("auth_type");
					this.Onauth_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weibo_id", DbType="VarChar(50)")]
		public string weibo_id
		{
			get
			{
				return this._weibo_id;
			}
			set
			{
				if ((this._weibo_id != value))
				{
					this.Onweibo_idChanging(value);
					this.SendPropertyChanging();
					this._weibo_id = value;
					this.SendPropertyChanged("weibo_id");
					this.Onweibo_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qq_weibo", DbType="VarChar(50)")]
		public string qq_weibo
		{
			get
			{
				return this._qq_weibo;
			}
			set
			{
				if ((this._qq_weibo != value))
				{
					this.Onqq_weiboChanging(value);
					this.SendPropertyChanging();
					this._qq_weibo = value;
					this.SendPropertyChanged("qq_weibo");
					this.Onqq_weiboChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_welcome_text", DbType="VarChar(300)")]
		public string welcome_text
		{
			get
			{
				return this._welcome_text;
			}
			set
			{
				if ((this._welcome_text != value))
				{
					this.Onwelcome_textChanging(value);
					this.SendPropertyChanging();
					this._welcome_text = value;
					this.SendPropertyChanged("welcome_text");
					this.Onwelcome_textChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_template_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string template_name
		{
			get
			{
				return this._template_name;
			}
			set
			{
				if ((this._template_name != value))
				{
					this.Ontemplate_nameChanging(value);
					this.SendPropertyChanging();
					this._template_name = value;
					this.SendPropertyChanged("template_name");
					this.Ontemplate_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_time", DbType="DateTime NOT NULL")]
		public System.DateTime create_time
		{
			get
			{
				return this._create_time;
			}
			set
			{
				if ((this._create_time != value))
				{
					this.Oncreate_timeChanging(value);
					this.SendPropertyChanging();
					this._create_time = value;
					this.SendPropertyChanged("create_time");
					this.Oncreate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_id", DbType="Int")]
		public System.Nullable<int> admin_id
		{
			get
			{
				return this._admin_id;
			}
			set
			{
				if ((this._admin_id != value))
				{
					this.Onadmin_idChanging(value);
					this.SendPropertyChanging();
					this._admin_id = value;
					this.SendPropertyChanged("admin_id");
					this.Onadmin_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class wifi_guest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _wifi_guest_type_id;
		
		private int _wifi_guest_group_id;
		
		private string _login_name;
		
		private System.Nullable<bool> _is_verfiymobile;
		
		private string _nickname;
		
		private string _province_name;
		
		private string _city_name;
		
		private int _merchant_Id;
		
		private System.Nullable<System.DateTime> _last_login_time;
		
		private string _last_login_token;
		
		private string _last_gw_id;
		
		private string _last_ip;
		
		private string _last_mac;
		
		private System.Nullable<int> _last_incoming;
		
		private System.Nullable<int> _last_outgoing;
		
		private string _last_stage;
		
		private System.Nullable<System.DateTime> _last_update_time;
		
		private bool _is_employee;
		
		private bool _is_online;
		
		private System.Nullable<bool> _is_goout;
		
		private System.DateTime _create_time;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onwifi_guest_type_idChanging(int value);
    partial void Onwifi_guest_type_idChanged();
    partial void Onwifi_guest_group_idChanging(int value);
    partial void Onwifi_guest_group_idChanged();
    partial void Onlogin_nameChanging(string value);
    partial void Onlogin_nameChanged();
    partial void Onis_verfiymobileChanging(System.Nullable<bool> value);
    partial void Onis_verfiymobileChanged();
    partial void OnnicknameChanging(string value);
    partial void OnnicknameChanged();
    partial void Onprovince_nameChanging(string value);
    partial void Onprovince_nameChanged();
    partial void Oncity_nameChanging(string value);
    partial void Oncity_nameChanged();
    partial void Onmerchant_IdChanging(int value);
    partial void Onmerchant_IdChanged();
    partial void Onlast_login_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onlast_login_timeChanged();
    partial void Onlast_login_tokenChanging(string value);
    partial void Onlast_login_tokenChanged();
    partial void Onlast_gw_idChanging(string value);
    partial void Onlast_gw_idChanged();
    partial void Onlast_ipChanging(string value);
    partial void Onlast_ipChanged();
    partial void Onlast_macChanging(string value);
    partial void Onlast_macChanged();
    partial void Onlast_incomingChanging(System.Nullable<int> value);
    partial void Onlast_incomingChanged();
    partial void Onlast_outgoingChanging(System.Nullable<int> value);
    partial void Onlast_outgoingChanged();
    partial void Onlast_stageChanging(string value);
    partial void Onlast_stageChanged();
    partial void Onlast_update_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onlast_update_timeChanged();
    partial void Onis_employeeChanging(bool value);
    partial void Onis_employeeChanged();
    partial void Onis_onlineChanging(bool value);
    partial void Onis_onlineChanged();
    partial void Onis_gooutChanging(System.Nullable<bool> value);
    partial void Onis_gooutChanged();
    partial void Oncreate_timeChanging(System.DateTime value);
    partial void Oncreate_timeChanged();
    #endregion
		
		public wifi_guest()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wifi_guest_type_id", DbType="Int NOT NULL")]
		public int wifi_guest_type_id
		{
			get
			{
				return this._wifi_guest_type_id;
			}
			set
			{
				if ((this._wifi_guest_type_id != value))
				{
					this.Onwifi_guest_type_idChanging(value);
					this.SendPropertyChanging();
					this._wifi_guest_type_id = value;
					this.SendPropertyChanged("wifi_guest_type_id");
					this.Onwifi_guest_type_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wifi_guest_group_id", DbType="Int NOT NULL")]
		public int wifi_guest_group_id
		{
			get
			{
				return this._wifi_guest_group_id;
			}
			set
			{
				if ((this._wifi_guest_group_id != value))
				{
					this.Onwifi_guest_group_idChanging(value);
					this.SendPropertyChanging();
					this._wifi_guest_group_id = value;
					this.SendPropertyChanged("wifi_guest_group_id");
					this.Onwifi_guest_group_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login_name", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string login_name
		{
			get
			{
				return this._login_name;
			}
			set
			{
				if ((this._login_name != value))
				{
					this.Onlogin_nameChanging(value);
					this.SendPropertyChanging();
					this._login_name = value;
					this.SendPropertyChanged("login_name");
					this.Onlogin_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_verfiymobile", DbType="Bit")]
		public System.Nullable<bool> is_verfiymobile
		{
			get
			{
				return this._is_verfiymobile;
			}
			set
			{
				if ((this._is_verfiymobile != value))
				{
					this.Onis_verfiymobileChanging(value);
					this.SendPropertyChanging();
					this._is_verfiymobile = value;
					this.SendPropertyChanged("is_verfiymobile");
					this.Onis_verfiymobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nickname", DbType="VarChar(45)")]
		public string nickname
		{
			get
			{
				return this._nickname;
			}
			set
			{
				if ((this._nickname != value))
				{
					this.OnnicknameChanging(value);
					this.SendPropertyChanging();
					this._nickname = value;
					this.SendPropertyChanged("nickname");
					this.OnnicknameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province_name", DbType="VarChar(45)")]
		public string province_name
		{
			get
			{
				return this._province_name;
			}
			set
			{
				if ((this._province_name != value))
				{
					this.Onprovince_nameChanging(value);
					this.SendPropertyChanging();
					this._province_name = value;
					this.SendPropertyChanged("province_name");
					this.Onprovince_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city_name", DbType="VarChar(45)")]
		public string city_name
		{
			get
			{
				return this._city_name;
			}
			set
			{
				if ((this._city_name != value))
				{
					this.Oncity_nameChanging(value);
					this.SendPropertyChanging();
					this._city_name = value;
					this.SendPropertyChanged("city_name");
					this.Oncity_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_merchant_Id", DbType="Int NOT NULL")]
		public int merchant_Id
		{
			get
			{
				return this._merchant_Id;
			}
			set
			{
				if ((this._merchant_Id != value))
				{
					this.Onmerchant_IdChanging(value);
					this.SendPropertyChanging();
					this._merchant_Id = value;
					this.SendPropertyChanged("merchant_Id");
					this.Onmerchant_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_login_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> last_login_time
		{
			get
			{
				return this._last_login_time;
			}
			set
			{
				if ((this._last_login_time != value))
				{
					this.Onlast_login_timeChanging(value);
					this.SendPropertyChanging();
					this._last_login_time = value;
					this.SendPropertyChanged("last_login_time");
					this.Onlast_login_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_login_token", DbType="VarChar(45)")]
		public string last_login_token
		{
			get
			{
				return this._last_login_token;
			}
			set
			{
				if ((this._last_login_token != value))
				{
					this.Onlast_login_tokenChanging(value);
					this.SendPropertyChanging();
					this._last_login_token = value;
					this.SendPropertyChanged("last_login_token");
					this.Onlast_login_tokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_gw_id", DbType="VarChar(45)")]
		public string last_gw_id
		{
			get
			{
				return this._last_gw_id;
			}
			set
			{
				if ((this._last_gw_id != value))
				{
					this.Onlast_gw_idChanging(value);
					this.SendPropertyChanging();
					this._last_gw_id = value;
					this.SendPropertyChanged("last_gw_id");
					this.Onlast_gw_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_ip", DbType="VarChar(45)")]
		public string last_ip
		{
			get
			{
				return this._last_ip;
			}
			set
			{
				if ((this._last_ip != value))
				{
					this.Onlast_ipChanging(value);
					this.SendPropertyChanging();
					this._last_ip = value;
					this.SendPropertyChanged("last_ip");
					this.Onlast_ipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_mac", DbType="VarChar(45)")]
		public string last_mac
		{
			get
			{
				return this._last_mac;
			}
			set
			{
				if ((this._last_mac != value))
				{
					this.Onlast_macChanging(value);
					this.SendPropertyChanging();
					this._last_mac = value;
					this.SendPropertyChanged("last_mac");
					this.Onlast_macChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_incoming", DbType="Int")]
		public System.Nullable<int> last_incoming
		{
			get
			{
				return this._last_incoming;
			}
			set
			{
				if ((this._last_incoming != value))
				{
					this.Onlast_incomingChanging(value);
					this.SendPropertyChanging();
					this._last_incoming = value;
					this.SendPropertyChanged("last_incoming");
					this.Onlast_incomingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_outgoing", DbType="Int")]
		public System.Nullable<int> last_outgoing
		{
			get
			{
				return this._last_outgoing;
			}
			set
			{
				if ((this._last_outgoing != value))
				{
					this.Onlast_outgoingChanging(value);
					this.SendPropertyChanging();
					this._last_outgoing = value;
					this.SendPropertyChanged("last_outgoing");
					this.Onlast_outgoingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_stage", DbType="VarChar(45)")]
		public string last_stage
		{
			get
			{
				return this._last_stage;
			}
			set
			{
				if ((this._last_stage != value))
				{
					this.Onlast_stageChanging(value);
					this.SendPropertyChanging();
					this._last_stage = value;
					this.SendPropertyChanged("last_stage");
					this.Onlast_stageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_update_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> last_update_time
		{
			get
			{
				return this._last_update_time;
			}
			set
			{
				if ((this._last_update_time != value))
				{
					this.Onlast_update_timeChanging(value);
					this.SendPropertyChanging();
					this._last_update_time = value;
					this.SendPropertyChanged("last_update_time");
					this.Onlast_update_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_employee", DbType="Bit NOT NULL")]
		public bool is_employee
		{
			get
			{
				return this._is_employee;
			}
			set
			{
				if ((this._is_employee != value))
				{
					this.Onis_employeeChanging(value);
					this.SendPropertyChanging();
					this._is_employee = value;
					this.SendPropertyChanged("is_employee");
					this.Onis_employeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_online", DbType="Bit NOT NULL")]
		public bool is_online
		{
			get
			{
				return this._is_online;
			}
			set
			{
				if ((this._is_online != value))
				{
					this.Onis_onlineChanging(value);
					this.SendPropertyChanging();
					this._is_online = value;
					this.SendPropertyChanged("is_online");
					this.Onis_onlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_goout", DbType="Bit")]
		public System.Nullable<bool> is_goout
		{
			get
			{
				return this._is_goout;
			}
			set
			{
				if ((this._is_goout != value))
				{
					this.Onis_gooutChanging(value);
					this.SendPropertyChanging();
					this._is_goout = value;
					this.SendPropertyChanged("is_goout");
					this.Onis_gooutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_time", DbType="DateTime NOT NULL")]
		public System.DateTime create_time
		{
			get
			{
				return this._create_time;
			}
			set
			{
				if ((this._create_time != value))
				{
					this.Oncreate_timeChanging(value);
					this.SendPropertyChanging();
					this._create_time = value;
					this.SendPropertyChanged("create_time");
					this.Oncreate_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
